/**
 * Protocol ID define here by enum class
 * This file is generated by Python script. Do not edit!!!
 * Python version: v3.12.8
 * Script version: v0.1
 */

package org.example.controller

enum class ProtocolType(val value: Int) {
	// proto.player
	CLIENT_LOGIN_REQUEST(1001),
	PLAYER_INFO(1002),

	// proto.friend
	FRIEND_LIST_REQUEST(2001),
	FRIEND_LIST_RESPONSE(2002),
	FRIEND_APPLY_LIST_REQUEST(2003),
	FRIEND_APPLY_LIST_RESPONSE(2004),
	FRIEND_APPLIED_LIST_REQUEST(2005),
	FRIEND_APPLIED_LIST_RESPONSE(2006),
	SEND_APPLY_REQUEST(2007),
	SEND_APPLY_RESPONSE(2008),
	HANDLE_APPLIED(2009),
	HANDLE_APPLIED_RESULT(2010),
	BLACK_LIST_REQUEST(2011),
	BLACK_LIST_RESPONSE(2012),
	BLACK_LIST_INFO(2013),

	PROTO_TYPE_MAX(2014),
}
