/**
 * Protocol ID define here by enum class
 * This file is generated by Python script. Do not edit!!!
 * Python version: v3.12.8
 * Script version: v0.1
 */

package org.example.controller

enum class ProtocolType(val value: Int) {
	// proto.player
	CLIENT_LOGIN_REQUEST(1001),
	PLAYER_INFO(1002),

	// proto.friend
	FRIEND_REQUEST(2001),
	FRIEND_RESPONSE(2002),
	FRIEND_APPLY_REQUEST(2003),
	FRIEND_APPLY_RESPONSE(2004),
	FRIEND_APPLIED_REQUEST(2005),
	FRIEND_APPLIED_RESPONSE(2006),
	SEND_APPLY_REQUEST(2007),
	SEND_APPLY_RESPONSE(2008),
	FRIEND_APPLIED_HANDLE(2009),
	FRIEND_APPLIED_RESULT(2010),
	BLACK_LIST_REQUEST(2011),
	BLACK_LIST_RESPONSE(2012),

	PROTO_TYPE_MAX(2013),
}
