/**
 * Object Relational Mapping Kotlin object definition
 * This file is generated by Python script. Do not edit!!!
 * Python version: v3.12.9
 * Script version: v0.1
 * Source file: /sql/appearance
 */

package org.example.table

import org.jetbrains.exposed.sql.Table

object AvatarTable : Table() {
	val playerId = long("player_id")
	val index = integer("index")
	val expiredTime = long("expired_time").default(0)
	val activated = bool("activated").default(false)
	val inUsed = bool("in_used").default(false)
	override val primaryKey = PrimaryKey(playerId, index)
}
